CC = gcc
CFLAGS = -O -Wall -Werror=multichar -fwrapv

all: day1 day2

day1: day1/day1.c
	$(CC) $(CFLAGS) -g -o day1/day1 day1/day1.c

day2: day2/day2.c
	$(CC) $(CFLAGS) -g -o day2/day2 day2/day2.c

clean:
	rm -f *.o d1 *~
